// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgCode.proto

package org.lpf.proto;

public final class MsgCode {
  private MsgCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code GameCode}
   */
  public enum GameCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQ_REGISTER_CLIENT = 100001;</code>
     *
     * <pre>
     *请求注册客户端   
     * </pre>
     */
    REQ_REGISTER_CLIENT(0, 100001),
    ;

    /**
     * <code>REQ_REGISTER_CLIENT = 100001;</code>
     *
     * <pre>
     *请求注册客户端   
     * </pre>
     */
    public static final int REQ_REGISTER_CLIENT_VALUE = 100001;


    public final int getNumber() { return value; }

    public static GameCode valueOf(int value) {
      switch (value) {
        case 100001: return REQ_REGISTER_CLIENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameCode>() {
            public GameCode findValueByNumber(int number) {
              return GameCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.lpf.proto.MsgCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameCode[] VALUES = values();

    public static GameCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GameCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GameCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgCode.proto*%\n\010GameCode\022\031\n\023REQ_REGIS" +
      "TER_CLIENT\020\241\215\006B\030\n\rorg.lpf.protoB\007MsgCode"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
